export type LessonLayout = 'landscape' | 'portrait';
export type TimedWord = { start_ms: number; end_ms: number; text: string };
export type LessonRecording = {
  id: string;
  file: string;
  audioHash: string;
  durationMs: number;
  words?: TimedWord[];
  questionAtMs?: number | null;
  cues: Array<{ id: string; atMs: number }>;
  contentAudit: { faithful: boolean; issues: string[] };
};
export type VisualSpec = { renderer: string; params: Record<string, unknown> };
export type LessonQuestion = {
  id: string;
  english: string;
  title: string;
  options: string[];
  englishOptions: string[];
  correct: number;
  explanation: string;
  englishAnswer: string;
  feedbackId: string;
  hint: string;
  attempt: 'choice' | 'choice-and-written' | 'written';
  readingParts?: Array<{ text: string; atMs: number; language: 'ar' | 'en' }>;
  feedbackParts?: Array<{ text: string; atMs: number; language: 'ar' | 'en' }>;
  answerReasoning?: string;
  writtenLabel?: string;
  writtenPlaceholder?: string;
  image?: { file: string; alt: string };
  contextVisual?: VisualSpec;
  readingVisual?: VisualSpec;
  feedbackVisual?: VisualSpec;
};
export type PackageScene = {
  id: string;
  title: string;
  takeaway: string;
  tip: string;
  script: string;
  check: string;
  visual: VisualSpec;
  recordingId: string;
  question?: LessonQuestion;
};
export type LessonPackage = {
  schemaVersion: 1;
  delivery: 'recorded';
  lessonId: string;
  curriculumId: string;
  contentRevision: string;
  recordingVersion: string;
  title: string;
  englishTitle: string;
  curriculumTitle: string;
  lessonOrder: number;
  fps: number;
  dimensions: Record<LessonLayout, { width: number; height: number }>;
  scenes: PackageScene[];
  recordings: LessonRecording[];
  glossary: Array<{ term: string; meaning: string }>;
  sources: Array<{ title: string; locator: string; availability: string; url?: string }>;
  review: { heading: string; summary: string };
  guide?: { image: string; name: string };
};
